---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
    linkerd: sidecar
  namespace: helloworld
spec:
  replicas: 3
  template:
    metadata:
      name: hello
      labels:
        app: hello
        linkerd: sidecar
    spec:
      serviceAccountName: helloworld
      volumes:
        - name: linkerd-config
          configMap:
            name: linkerd-config
      containers:
        - name: helloworld
          image: buoyantio/helloworld:latest
          args:
            - "-target"
            - "world"
          env:
            - name: http_proxy
              value: localhost:4140
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: helloworld
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - port: 7777
      name: http
    - port: 9990
      name: linkerd-admin
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
  namespace: helloworld
  annotations:
    kubernetes.io/ingress.class: linkerd
spec:
  rules:
    - host: hello.gavel.bengo4.com
      http:
        paths:
          - backend:
              serviceName: hello
              servicePort: http

