---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-l5d-config
data:
  config.yaml: |-
    admin:
      port: 9990
    telemetry:
      - kind: io.l5d.zipkin
        host: zipkin.default.svc.cluster.local
        port: 9410
        sampleRate: 1.0
    namers:
      - kind: io.l5d.k8s
    routers:
      - protocol: http
        httpAccessLog: /dev/stdout
        label: http-incoming
        interpreter:
          kind: io.l5d.namerd
          dst: /$/inet/namerd.default.svc.cluster.local/4100
          namespace: {{ default .Release.Namespace .Values.ns }}
          transformers:
          - kind: io.l5d.port
            port: 4141
        servers:
          - port: 4140
            ip: 0.0.0.0
      - protocol: http
        httpAccessLog: /dev/stdout
        label: http-outgoing
        interpreter:
          kind: io.l5d.namerd
          dst: /$/inet/namerd.default.svc.cluster.local/4100
          namespace: {{ .Values.ns | default .Release.Namespace }}
          transformers:
          - kind: io.l5d.k8s.localnode
        servers:
          - port: 4141
            ip: 0.0.0.0
