---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-namerctl-script
data:
  createNs.sh: |-
    #!/bin/sh

    set -e

    if namerctl dtab get {{ default .Release.Namespace .Values.ns }} > /dev/null 2>&1; then
      echo "{{ default .Release.Namespace .Values.ns }} namespace already exists"
    else
      echo "{{ default .Release.Namespace .Values.ns }} namespace does not exist. Creating...."

      echo "
      {{- if .Values.ns }}
      /svc => /withLabel/{{ .Values.ns }};
      /withLabel => /#/swap;
      /swap => /#/io.l5d.k8s.rg/{{ .Release.Namespace }}/http;
      {{- else }}
      /svc => /#/io.l5d.k8s/{{ .Release.Namespace }}/http;
      {{- end }}
      " | namerctl dtab create {{ default .Release.Namespace .Values.ns }} -
    fi
