---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hello.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-hello
    release: {{ .Release.Name }}
  ports:
    - port: 7777
      name: http
    - port: 9990
      name: linkerd-admin
