---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
  annotations:
    kubernetes.io/ingress.class: linkerd
spec:
  rules:
    - host: hello-{{ .Release.Namespace }}.gavel.bengo4.com
      http:
        paths:
          - backend:
              serviceName: hello
              servicePort: http

