{{- $svcPfx := (index .Values "l5d-mesh" "svcPfx") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ default .Release.Name $svcPfx }}-world
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-world
    release: {{ .Release.Name }}
  ports:
    - port: 7777
      name: http
    - port: 9990
      name: linkerd-admin
